#!/usr/bin/expect -f

# Program name:	get_logs
# Created by:	Talon Jones
# Created:	29 Oct. 2016
# Updated:	16 Nov. 2016
# Purpose:	Retrieve any iperf log files from boards listed in ipconfig.txt.
# Usage:	./get_logs [IP] [PW] [Name] [Path]

set timeout -1
set addr [lindex $argv 0]
set pw [lindex $argv 1]
set board [lindex $argv 2]
set logpath [lindex $argv 3]
set prompt "$"
set log1 "log_test1"
set log2 "log_test2"
set log3 "log_test3"
set slog "nohup.out"


eval spawn scp odroid@$addr:$log1 $logpath/$log1/$board-log1.txt
expect {
	"(yes/no)" { send "yes\r"; exp_continue }
	"password:" { send -- "$pw\r" }
}

eval spawn scp odroid@$addr:$log2 $logpath/$log2/$board-log2.txt
expect {
        "(yes/no)" { send "yes\r"; exp_continue }
        "password:" { send -- "$pw\r" }
}

eval spawn scp odroid@$addr:$log3 $logpath/$log3/$board-log3.txt
expect {
        "(yes/no)" { send "yes\r"; exp_continue }
        "password:" { send -- "$pw\r" }
}

eval spawn scp odroid@$addr:$slog $logpath/servers/$board-server.txt
expect {
        "(yes/no)" { send "yes\r"; exp_continue }
        "password:" { send -- "$pw\r" }
}

sleep 5

expect -ex $prompt {
	exit
}
