#!/usr/bin/expect -f

# Program name: test_iperf
# Created by:   Talon Jones
# Created:      17 Oct. 2016
# Updated:      18 Oct. 2016
# Purpose:      Expect script to ssh into [IP]s and initiate selected iPerf test.
# Usage:        ./test_iperf [IPclient] [IPserver] [PW] [Test] [Duration]

set timeout -1
set addrC [lindex $argv 0]
set addrS [lindex $argv 1]
set pw [lindex $argv 2]
set test [lindex $argv 3]
set dur [lindex $argv 4]
set prompt "$"

if {$test == "1"} {
	set test "iperf3 -c $addrS -u -t $dur"
	puts "$test\n"
} elseif {$test == "2"} {
	set test "iperf3 -c $addrS -t $dur"
	puts "2\n"
} elseif {$test == "3"} {
	puts "3\n"
}

eval spawn ssh -o PubkeyAuthentication=no $addrS
expect {
        "(yes/no)" { send "yes\r"; exp_continue }
        "password:"
}
send -- "$pw\r"

expect -ex $prompt
send -- "kill \$(ps -aux | grep -m 1 \"iperf3\" \| awk \'\{printf \$2\}\')\r"
sleep 1
expect -ex $prompt
send -- "nohup iperf3 -p 3344 -s &\r"
expect -ex $prompt
send -- "disown\r"

sleep 1
expect -ex $prompt
#interact
send -- "logout\r"

sleep 2

eval spawn ssh -o PubkeyAuthentication=no $addrC
expect {
	"(yes/no)" { send "yes\r"; exp_continue}
	"password:"
}
send -- "$pw\r"

expect -ex $prompt
interact
